# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Dockerfile for GraphQL Schema MCP Server
# Uses Node.js Alpine for a small footprint
FROM node:lts-alpine AS base

# Create app directory
WORKDIR /app

# Copy package manifest(s)
COPY package.json package-lock.json ./

# Install dependencies (ignore any prepare scripts)
RUN npm ci --ignore-scripts --production

# Copy source files into image
COPY index.mjs tsconfig.json .

# Provide a minimal default schema to prevent startup failure
RUN printf "type Query { _empty: String }" > schema.graphqls

# Default command to start server
ENTRYPOINT ["node", "index.mjs"]
# The server will use schema.graphqls by default unless overridden via args
